### ISSUE TITLE
Mojang fixes this in 1.21.2?

### ISSUE THREAD

**Issue by diskria** [nvb-uy/boatbreakfix#2]
https://bugs.mojang.com/browse/MC-119369

the task status has changed to fixed, this means that the developers have finally decided to fix it!

**Comment by Franco227** [comment]
~~It isn't actually fixed yet, the Fix Version is set to Future Update, so this mod is still useful in the meantime~~

Edit: Nevermind, it's added in Snapshot 24w37a and will therefore make it to 1.21.2 like you said.

**Comment by nvb-uy** [comment]
Finally, the mod will stay for 1.21.1 and downwards tho
